services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - PGUSER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - OPENFN_POSTGRESQL_DB=${OPENFN_POSTGRESQL_DB}
      - OPENFN_POSTGRESQL_USERNAME=${OPENFN_POSTGRESQL_USERNAME}
      - OPENFN_POSTGRESQL_PASSWORD=${OPENFN_POSTGRESQL_PASSWORD}
    volumes:
      # If PGDATA_PATH is set, use it as a bind mount. Otherwise, use the named volume 'pgdata'.
      - ${PGDATA_PATH:-pgdata}:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
